### ISSUE TITLE
Ошибка при активации плагина Button visually impaired 2.2.0

### ISSUE THREAD

**Issue by GordonBreazz** [veks/button-visually-impaired-javascript#21]
Версия Wordpress последняя. Удаление cyr2lat ничего не меняет. При активации плагина возникает ошибка. 

Fatal error: Uncaught Error: Class 'Bvi\Core\FieldsAdmin\Fields' not found in ../public_html/wp-content/plugins/button-visually-impaired/include/src/Core/FieldsAdmin/Text.php:17 

Stack trace: 
#0 ../public_html/wp-content/plugins/cyr2lat/vendor/composer/ClassLoader.php(480): include() 
#1 ../public_html/wp-content/plugins/cyr2lat/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Bvi\\Core\\Fields...') 
#3 ../public_html/wp-content/plugins/button-visually-impaired/include/src/Core/Admin.php(48): spl_autoload_call('Bvi\\Core\\Fields...') 
#4 ../public_html/wp-content/plugins/button-visually-impaired/include/src/Core/Loader.php(96): Bvi\Core\Admin->__construct()
#5 ../public_html/wp-content/plugins/button-visually-impaired/Button-visually-impaired.php(62): Bvi\Core\Loader->register() 
#6 /home/k/k in ../public_html/wp-content/plugins/button-visually-impaired/include/src/Core/FieldsAdmin/Text.php on line 17

**Comment by veks** [comment]
@GordonBreazz, попробуй удалить папку через ftp /public_html/wp-content/plugins/button-visually-impaired/

**Comment by GordonBreazz** [comment]
не помогает, та же ошибка. 
"Fatal error: Uncaught Error: Class 'Bvi\Core\FieldsAdmin\Fields' not found in /home/k/kforum/cbs-uu.ru/public_html/wp-content/plugins/button-visually-impaired/include/src/Core/FieldsAdmin/Text.php:17 Stack trace: #0 /home/k/kforum/cbs-uu.ru/public_html/wp-content/plugins/cyr2lat/vendor/composer/ClassLoader.php(480): include() #1 /home/k/kforum/cbs-uu.ru/public_html/wp-content/plugins/cyr2lat/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/home/k/kforum/...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Bvi\\Core\\Fields...') #3 /home/k/kforum/cbs-uu.ru/public_html/wp-content/plugins/button-visually-impaired/include/src/Core/Admin.php(48): spl_autoload_call('Bvi\\Core\\Fields...') #4 /home/k/kforum/cbs-uu.ru/public_html/wp-content/plugins/button-visually-impaired/include/src/Core/Loader.php(96): Bvi\Core\Admin->__construct() #5 /home/k/kforum/cbs-uu.ru/public_html/wp-content/plugins/button-visually-impaired/Button-visually-impaired.php(64): Bvi\Core\Loader->register() #6 /home/k/k in /home/k/kforum/cbs-uu.ru/public_html/wp-content/plugins/button-visually-impaired/include/src/Core/FieldsAdmin/Text.php on line 17"
