### ISSUE TITLE
Фатальная ошибка при активации

### ISSUE THREAD

**Issue by xakeryonok** [veks/button-visually-impaired-javascript#31]
При активации плагина появляется ошибка.

Плагин не был активирован, потому что он вызвал фатальную ошибку.

Fatal error: Uncaught Error: Class "Bvi\Core\FieldsAdmin\Color" not found in /var/www/.../wp-content/plugins/button-visually-impaired/include/src/Core/Admin.php:51 Stack trace: #0 /var/www/.../wp-content/plugins/button-visually-impaired/include/src/Core/Loader.php(96): Bvi\Core\Admin->__construct() #1 /var/www/.../wp-content/plugins/button-visually-impaired/Button-visually-impaired.php(64): Bvi\Core\Loader->register() #2 /var/www/.../wp-admin/includes/plugin.php(2288): include_once('/var/www/...') #3 /var/www/.../wp-admin/plugins.php(192): plugin_sandbox_scrape('button-visually...') #4 {main} thrown in /var/www/.../wp-content/plugins/button-visually-impaired/include/src/Core/Admin.php on line 51

Версия Wordpress: 5.9
Тема: the7 v10.3.0 
php: 8.1

Версия плагина: 2.3.0

**Comment by xakeryonok** [comment]
Прошу помощи. Сам не в силах разобраться...

**Comment by veks** [comment]
Привет @xakeryonok, попробуй удалить плагин и заново установить
